# Generated by Django 3.1.1 on 2020-09-10 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_am', models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization')], max_length=30)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_introduction', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('region_or_state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('interest', models.CharField(max_length=1000)),
                ('education_level', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regular_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.CharField(blank=True, max_length=500, null=True)),
                ('help_you_need', models.CharField(blank=True, max_length=2000, null=True)),
                ('demo_in_text', models.TextField(blank=True, null=True)),
                ('demo', models.FileField(blank=True, null=True, upload_to='demo')),
                ('regular_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.regularuser')),
            ],
        ),
    ]
