# Generated by Django 3.1.1 on 2020-09-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_donor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='education_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='interest',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Starred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.donor')),
                ('starred', models.ManyToManyField(related_name='starred', to='profiles.Grievance')),
            ],
        ),
    ]
