# Generated by Django 3.1.1 on 2020-09-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200910_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='i_am',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Organization', 'Organization')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
